[New sample] Show labels on layers in 3D
Esri/arcgis-maps-sdk-dotnet-samples pull request #1181
Opened 2022-12-28 21:44 UTC by williambohrmann3

# Description

New sample for showing labels on layers in 3D scenes.

## Type of change

- [ ] Bug fix
- [ ] New sample implementation
- [ ] Sample viewer enhancement
- [ ] Other enhancement

**Platforms tested on**:

- [ ] WPF .NET 6
- [ ] WPF Framework
- [ ] WinUI
- [ ] MAUI Windows
- [ ] MAUI Android
- [ ] MAUI iOS
- [ ] MAUI Mac Catalyst

## Checklist

- [ ] Self-review of changes
- [ ] Runs and compiles on all active platforms
- [ ] Branch is up to date with the latest main/v.next
- [ ] All merge conflicts have been resolved
- [ ] There are no warnings related to changes
- [ ] No unrelated changes have been made to any other code or project files
- [ ] `sample_sync.py` runs without making changes
- [ ] Codemaid and XAML styler extensions have been run on every changed file
- [ ] Code is commented with correct formatting
- [ ] All variable and method names are good and make sense
- [ ] There is no leftover commented code
- [ ] Screenshots are correct size and display in description tab (800 x 600 on Windows, 600 height mobile screenshots for MAUI)

2022-12-28 22:17 UTC, mstefarov commented on src/MAUI/Maui.Samples/Samples/Scene/ShowLabelsOnLayer3D/ShowLabelsOnLayer3D.xaml.cs
> +                MySceneView.Scene = new Scene(websceneItem);
IMO this sample could be simplified to just creating a Scene from an item URL, e.g.

```cs
        private const string ItemUrl = "https://www.arcgis.com/home/item.html?id=850dfee7d30f4d9da0ebca34a533c169";
// ...
        MySceneView.Scene = new Scene(new Uri(ItemUrl));
```

2022-12-28 22:17 UTC, mstefarov commented on src/MAUI/Maui.Samples/Samples/Scene/ShowLabelsOnLayer3D/readme.metadata.json
> +  ],
I'd consider `LabelDefinition` and `ArcadeLabelExpression` to be very relevant here, much more so than `PortalItem`.  Adding items here will help users discover samples by adding links to the API reference.

2022-12-28 22:17 UTC, mstefarov commented on src/MAUI/Maui.Samples/Samples/Scene/ShowLabelsOnLayer3D/ShowLabelsOnLayer3D.xaml.cs
> +    [ArcGIS.Samples.Shared.Attributes.OfflineData()]
Doesn't look like this sample actually uses any offline data -- you can remove this attribute.

2022-12-28 22:31 UTC, ZackAllen requested changes

2022-12-28 22:31 UTC, ZackAllen commented on src/WPF/WPF.Viewer/Samples/Scene/ShowLabelsOnLayer3D/readme.md
> +1. Create an `ArcGISScene` from a portal, then load.
```suggestion
1. Create an `Scene` from a portal, then load.
```
It is just called `Scene` in the .NET API.

2022-12-28 22:31 UTC, ZackAllen commented on src/WPF/WPF.Viewer/Samples/Scene/ShowLabelsOnLayer3D/ShowLabelsOnLayer3D.xaml.cs
> +                // Create the portal item.
Comment for every line is too much. We should cut back on the comments.

2022-12-28 22:31 UTC, ZackAllen commented on src/MAUI/Maui.Samples/Samples/Scene/ShowLabelsOnLayer3D/ShowLabelsOnLayer3D.xaml.cs
> +using System;
Codemaid has not been run on this file. Re-reun codemaid and xaml styler on everything with the correct configurations.

2022-12-28 22:31 UTC, ZackAllen commented on src/WPF/WPF.Viewer/Samples/Scene/ShowLabelsOnLayer3D/readme.md
> +portal, scene, web scene
We should add tags related to labelling and 3d.

2022-12-28 22:31 UTC, ZackAllen commented on src/WPF/WPF.Viewer/Samples/Scene/ShowLabelsOnLayer3D/ShowLabelsOnLayer3D.xaml
> +    <Grid>
Grid is unneeded.

2022-12-29 00:00 UTC, ZackAllen requested changes

2022-12-29 17:35 UTC, mstefarov approved these changes

2022-12-29 17:38 UTC, ZackAllen requested changes

2022-12-29 17:38 UTC, ZackAllen commented on src/WPF/WPF.Viewer/App.xaml
> -﻿<Application x:Class="ArcGIS.WPF.Viewer.App"
unrelated change

2022-12-29 17:38 UTC, ZackAllen commented on src/WPF/WPF.Viewer/Resources/ControlStyles.xaml
> -﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
unrelated change

2022-12-29 18:05 UTC, ZackAllen approved these changes

2022-12-29 18:07 UTC, merged