New sample: Display route later
Esri/arcgis-maps-sdk-dotnet-samples pull request #1198
Opened 2023-03-08 00:17 UTC by williambohrmann3

# Description

Create a new sample display route layer.

## Type of change

- New sample implementation

## Platforms tested on

- [ ] WPF .NET 6
- [ ] WPF Framework
- [ ] WinUI
- [ ] MAUI WinUI
- [ ] MAUI Android
- [ ] MAUI iOS
- [ ] MAUI MacCatalyst

## Checklist

- [ ] Self-review of changes
- [ ] All changes work as expected on all affected platforms
- [ ] There are no warnings related to changes
- [ ] Code is commented and follows .NET conventions and standards
- [ ] Codemaid and XAML styler extensions have been run on every changed file
- [ ] No unrelated changes have been made to any other code or project files
- [ ] Screenshots are correct size and display in description tab (800 x 600 on Windows, 600 height mobile screenshots for MAUI)

2023-03-08 00:30 UTC, williambohrmann3 commented
Did not want to take MAUI screenshot in Android considering that we're switching to Windows for screenshots - awaiting screenshot tool.

2023-03-10 16:09 UTC, duffh requested changes

2023-03-10 19:08 UTC, williambohrmann3 commented on src/MAUI/Maui.Samples/Samples/Layers/DisplayRouteLayer/DisplayRouteLayer.xaml
> +                <Switch HorizontalOptions="Start" Toggled="Switch_Toggled" />
In MAUI I think it makes sense to always display the directions. The show/hide toggle doesn't make sense on a mobile platform where the `SampleControlPanel` style causes the `MapView` to be resized.

2023-03-11 01:05 UTC, amweis226 reviewed
The layer not being shown in it's entirety is somewhat jarring, but also relatively difficult to fix given the symbology used (particularly the green "start" symbol). Would probably help to zoom out slightly when you take your final screenshots. Other than this and some minor suggested grammatical changes, it looks good. Good job.

2023-03-20 15:35 UTC, duffh commented on src/MAUI/Maui.Samples/Samples/Layers/DisplayRouteLayer/DisplayRouteLayer.xaml
> +                <Switch HorizontalOptions="Start" Toggled="Switch_Toggled" />
We use the show/hide logic on other mobile samples to my knowledge. The `SampleControlPanel` does not need to cause the `MapView` to be resized.

2023-03-21 00:19 UTC, williambohrmann3 commented on src/MAUI/Maui.Samples/Samples/Layers/DisplayRouteLayer/readme.md
> +
nice catch!

2023-03-22 14:35 UTC, duffh approved these changes

2023-03-22 17:59 UTC, merged