Create "Add dynamic entity layer" Sample
Esri/arcgis-maps-sdk-dotnet-samples pull request #1201
Opened 2023-03-21 12:31 UTC by amweis226

# Description

Adds new "Add dynamic entity layer" sample to the sample viewer.

## Type of change

- New sample implementation

## Platforms tested on

- [ ] WPF .NET 6
- [ ] WPF Framework
- [ ] WinUI
- [ ] MAUI WinUI
- [ ] MAUI Android
- [ ] MAUI iOS
- [ ] MAUI MacCatalyst

## Checklist

- [ ] Self-review of changes
- [ ] All changes work as expected on all affected platforms
- [ ] There are no warnings related to changes
- [ ] Code is commented and follows .NET conventions and standards
- [ ] Codemaid and XAML styler extensions have been run on every changed file
- [ ] No unrelated changes have been made to any other code or project files
- [ ] Screenshots are correct size and display in description tab (800 x 600 on Windows, 600 height mobile screenshots for MAUI)

2023-03-22 00:28 UTC, amweis226 commented
There is issue with the label for previous observations slider in MAUI. This platform's version doesn't have tick and frequency controls like WinUI and WPF so snapping values to an integer is not possible directly on the label control. This does not impact the functionality of the app. Any suggestions are welcome.

2023-03-22 22:46 UTC, williambohrmann3 requested changes
Functional, looks great, just needs a few final UI tweaks.

2023-03-22 22:46 UTC, williambohrmann3 commented on src/MAUI/Maui.Samples/Samples/Layers/AddDynamicEntityLayer/AddDynamicEntityLayer.xaml
> +                    <Label Grid.Row="0"
For this entire grid, I'd swap columns for each control, so the checkboxes in column 0 and labels in column 1. Adding VerticalOptions="Center" to both labels will align the label next to the checkbox.

2023-03-22 22:46 UTC, williambohrmann3 commented on src/MAUI/Maui.Samples/Samples/Layers/AddDynamicEntityLayer/AddDynamicEntityLayer.xaml
> +                <Grid>
```suggestion
                <Grid ColumnDefinitions="auto, auto" RowDefinitions="auto, auto">
```
Shorthand for column/row definitions.

2023-03-22 22:46 UTC, williambohrmann3 commented on src/MAUI/Maui.Samples/Samples/Layers/AddDynamicEntityLayer/AddDynamicEntityLayer.xaml
> +                       Text="{Binding Value, StringFormat='Observations per track ({0})'}"
I'd set the text of this label in the code behind, in your Slider_ValueChanged event handler. That way you're able to display EntitiesSlider.Value as a whole number.

2023-03-22 22:46 UTC, williambohrmann3 commented on src/WinUI/ArcGIS.WinUI.Viewer/Samples/Layers/AddDynamicEntityLayer/AddDynamicEntityLayer.xaml
> +                               Text="{Binding ElementName=EntitiesSlider, Path=Value}" />
For clarity, "Observations per track" should preface EntitiesSlider.Value

2023-03-28 14:03 UTC, duffh requested changes
MAUI and WPF looks great.

WinUI might be a little large in terms of UI.

Couldn't test MAUI iOS or MacCatalyst without 200.1 packages. 

I'd recommend merging in `v.next` to update the screenshots.

Your checks are failing, once everything has been addressed I'll take a look.

2023-03-28 23:52 UTC, williambohrmann3 requested changes
Desktop looks great. Two mobile issues.

2023-03-28 23:52 UTC, williambohrmann3 commented on src/MAUI/Maui.Samples/Samples/Layers/AddDynamicEntityLayer/AddDynamicEntityLayer.xaml
> +                <Label x:Name="previousObservationsLabel" Text="Previous observations per track: 5" />
When observations number changes from one to two digits (and vice versa), the MapView will subtly shrink/expand. This is a landscape orientation issue specific to mobile (noticed this on OnePlus Android device).

2023-03-28 23:52 UTC, williambohrmann3 commented on src/MAUI/Maui.Samples/Samples/Layers/AddDynamicEntityLayer/AddDynamicEntityLayer.xaml
> +                Style="{DynamicResource EsriSampleControlPanel}"
On iPhone Simulator (SE 3 and 14 Pro Max), if you start the sample in vertical mode, then rotate to horizontal mode, the control panel takes up the entire screen. If you start sample in horizontal mode, it'll display the control panel and map just fine. However, upon rotating the screen to vertical mode and back to horizontal mode, the map view is invisible.

2023-03-29 17:34 UTC, duffh approved these changes
Approved pending resolution of William's comments

2023-03-29 20:18 UTC, williambohrmann3 approved these changes

2023-03-29 23:31 UTC, merged