Follow plane when changing missions in Animate3DGraphic
Esri/arcgis-maps-sdk-dotnet-samples pull request #1212
Opened 2023-04-11 21:16 UTC by williambohrmann3

# Description

The scene's camera controller is null after Don't Follow button is clicked, keeping the camera in place. When changing missions, the camera should follow the plane, so the controller should be set to the OrbitGeoElementController. 

## Type of change

- Bug fix

## Platforms tested on

- [ ] WPF .NET 6
- [ ] WPF Framework
- [ ] WinUI
- [ ] MAUI WinUI
- [ ] MAUI Android
- [ ] MAUI iOS
- [ ] MAUI MacCatalyst

## Checklist

- [ ] Self-review of changes
- [ ] All changes work as expected on all affected platforms
- [ ] There are no warnings related to changes
- [ ] Code is commented and follows .NET conventions and standards
- [ ] Codemaid and XAML styler extensions have been run on every changed file
- [ ] No unrelated changes have been made to any other code or project files

2023-04-13 16:59 UTC, williambohrmann3 commented on src/MAUI/Maui.Samples/Samples/GraphicsOverlay/Animate3DGraphic/Animate3DGraphic.xaml
> +                WidthRequest="400"
This fixes a MacCatalyst specific UI issue where the border overlaps the buttons

2023-04-13 23:29 UTC, amweis226 requested changes
All platforms: text in mission button is left-justified, would look better centered like the other controls in that panel. "GrandCanyon" option is one word and also gets cut off by the picker

Maui Android: borders overlap in vertical mode, could use some help in horizontal mode. Worth noting that performance is not good on my simulator. Unsure if this is the case for others.

The "Maui android" issues need attention, the "all platforms" ones are less important.

2023-04-17 23:32 UTC, williambohrmann3 commented
MAUI UI has been updated to account for horizontal mode. On all platforms, all controls are now accessible.

2023-04-18 00:22 UTC, amweis226 commented
The controls are working properly now but in horizontal mode they take up about 80% of the screen, only a small sliver shows the SceneView

2023-04-18 00:26 UTC, amweis226 approved these changes

2023-04-19 15:30 UTC, duffh approved these changes

2023-04-19 21:05 UTC, merged