Add Data Path controls to Local Server Samples
Esri/arcgis-maps-sdk-dotnet-samples pull request #1244
Opened 2023-05-08 03:08 UTC by amweis226

# Description

Summary of the change and any relevant info.

## Type of change

- Sample viewer enhancement

## Platforms tested on

- [ ] WPF .NET 6
- [ ] WPF Framework
- [ ] WinUI

## Checklist

- [ ] Self-review of changes
- [ ] All changes work as expected on all affected platforms
- [ ] There are no warnings related to changes
- [ ] Code is commented and follows .NET conventions and standards
- [ ] Codemaid and XAML styler extensions have been run on every changed file
- [ ] No unrelated changes have been made to any other code or project files
- [ ] Screenshots are correct size and display in description tab (800 x 600 on Windows, MAUI mobile platforms use the MAUI Windows screenshot)

2023-05-11 15:26 UTC, duffh commented on src/WPF/WPF.Viewer/Samples/LocalServer/LocalServerMapImageLayer/LocalServerMapImageLayer.jpg
We should remove the path from the screenshot.

2023-05-11 15:32 UTC, duffh commented on src/WPF/WPF.Viewer/Samples/LocalServer/LocalServerFeatureLayer/LocalServerFeatureLayer.jpg
We have a `Current path` set in some samples but not others. Is this intentional?

2023-05-11 15:34 UTC, duffh commented on src/WPF/WPF.Viewer/Samples/LocalServer/LocalServerFeatureLayer/LocalServerFeatureLayer.xaml
> +                            Click="setTempPathButton_Click"
Event handlers and UI object names should start with a capital letter.

2023-05-11 18:42 UTC, williambohrmann3 requested changes
Glad your adding set path functionality to these samples.

2023-05-11 18:42 UTC, williambohrmann3 commented on src/WPF/WPF.Viewer/Samples/LocalServer/LocalServerGenerateElevationProfile/LocalServerGenerateElevationProfile.xaml
> +                    <Button Grid.Column="1"
Minor visual nitpick: buttons are up against each other and would look nicer with a small gap between them.

2023-05-11 18:42 UTC, williambohrmann3 commented on src/WPF/WPF.Viewer/Samples/LocalServer/LocalServerGenerateElevationProfile/LocalServerGenerateElevationProfile.xaml.cs
> +                Directory.CreateDirectory(userTempDataPath); // CreateDirectory won't overwrite if it already exists.
Our comment styling convention: "Comments should always be on their own line (don't place at the end of a line of code)."

2023-05-11 18:42 UTC, williambohrmann3 commented on src/WPF/WPF.Viewer/Samples/LocalServer/LocalServerGeoprocessing/LocalServerGeoprocessing.xaml
> +                    <Button Grid.Row="2"
Button width moving after setting path: this could be fixed by setting both column widths to * and setting the current path label's column span to 2.

2023-05-11 18:42 UTC, williambohrmann3 commented on src/WPF/WPF.Viewer/Samples/LocalServer/LocalServerServices/LocalServerServices.xaml
>                  Content="Start Local Server" />
Should we disable this button upon starting the sample, until the current path has been set to default or specified by user?

2023-05-11 18:42 UTC, williambohrmann3 commented on src/WPF/WPF.Viewer/Samples/LocalServer/LocalServerServices/LocalServerServices.xaml.cs
> +                // Set the local data path to content of tempDataPath box input by user
Periods.

2023-05-11 18:42 UTC, williambohrmann3 commented on src/WinUI/ArcGIS.WinUI.Viewer/Samples/LocalServer/LocalServerGenerateElevationProfile/LocalServerGenerateElevationProfile.xaml
> +                            Click="setTempPathButton_Click"
HorizontalAlignment = "Stretch" would make buttons consistent with your WPF implementation

2023-05-18 22:42 UTC, amweis226 commented
Closing this issue for now.

2023-05-18 22:42 UTC, closed without merging