WMS service catalog data
Esri/arcgis-maps-sdk-dotnet-samples pull request #1295
Opened 2023-09-18 18:14 UTC by williambohrmann3

# Description

- Updates the catalog data to an online service
- UI workarounds for long titles
- Update comments

## Type of change

- Bug fix

## Platforms tested on

- [x] WPF .NET 6
- [x] WPF Framework
- [x] WinUI
- [x] MAUI WinUI
- [x] MAUI Android
- [x] MAUI iOS
- [x] MAUI MacCatalyst

## Checklist

- [ ] Self-review of changes
- [ ] All changes work as expected on all affected platforms
- [ ] There are no warnings related to changes
- [ ] Code is commented and follows .NET conventions and standards
- [ ] Codemaid and XAML styler extensions have been run on every changed file
- [ ] No unrelated changes have been made to any other code or project files
- [ ] Screenshots are correct size and display in description tab (800 x 600 on Windows, MAUI mobile platforms use the MAUI Windows screenshot)

2023-09-20 14:23 UTC, duffh requested changes
Looks good, just a few comments.

2023-09-20 14:23 UTC, duffh commented on src/WinUI/ArcGIS.WinUI.Viewer/Samples/Layers/WmsServiceCatalog/WmsServiceCatalog.jpg
Minor UI issue here, the label is appearing behind the `ScrollViewer`. It is visible when you swipe across. 

![image](https://github.com/Esri/arcgis-maps-sdk-dotnet-samples/assets/99325835/c0d3798b-f757-4778-8ae5-03f6857ecbe3)

2023-09-20 14:23 UTC, duffh commented on src/WinUI/ArcGIS.WinUI.Viewer/Samples/Layers/WmsServiceCatalog/WmsServiceCatalog.xaml
> +                             SelectionChanged="ListSelectionChanged"
The `Grid.Row` value is set on the wrong UI element.

Fix UI issue with: 

```
<ScrollViewer Grid.Row="1"
              HorizontalScrollBarVisibility="Visible"
              HorizontalScrollMode="Enabled">
    <ListBox x:Name="MyDisplayList"
             SelectionChanged="ListSelectionChanged"
             SelectionMode="Single" />
</ScrollViewer>
```

2023-09-20 14:23 UTC, duffh commented on src/WinUI/ArcGIS.WinUI.Viewer/Samples/Layers/WmsServiceCatalog/WmsServiceCatalog.xaml.cs
Missing full stop at the end of the comment on line 77.

"Updates the map with the latest layer selection."

2023-09-20 14:23 UTC, duffh commented on src/WPF/WPF.Viewer/Samples/Layers/WmsServiceCatalog/WmsServiceCatalog.jpg
```
<Border Width="400" Style="{StaticResource BorderStyle}">
```

The above change removes the scroll bar when the sample first loads. It's not a big issue but it looks slightly nicer.

2023-09-20 14:23 UTC, duffh commented on src/MAUI/Maui.Samples/Samples/Layers/WmsServiceCatalog/wmsservicecatalog.jpg
There is something going on with the display of the `ListView`.

You might need to change the layout or width as the text wrapping looks odd.

2023-09-20 14:26 UTC, duffh commented on src/MAUI/Maui.Samples/Samples/Layers/WmsServiceCatalog/wmsservicecatalog.jpg
Increasing the width of the border didn't help it just made it look different but still not right. 

![image](https://github.com/Esri/arcgis-maps-sdk-dotnet-samples/assets/99325835/9c9fe33b-9cab-46c6-88d9-47e313e8da81)

2023-09-20 18:04 UTC, williambohrmann3 commented on src/MAUI/Maui.Samples/Samples/Layers/WmsServiceCatalog/wmsservicecatalog.jpg
Added platform-specific XAML to handle this.

2023-09-21 14:25 UTC, duffh approved these changes

2023-09-21 17:49 UTC, merged