New Sample: Snap geometry edits
Esri/arcgis-maps-sdk-dotnet-samples pull request #1442
Opened 2024-05-07 10:29 UTC by duffh

# Description

Implemented new sample to demonstrate how to use the Geometry Editor to edit a geometry and align it to existing geometries on a map.

Updated the sample sync python script to generate proper redirects, this has caused a number of readme changes to be changed which are not directly relevant to the sample code. 

## Type of change

- New sample implementation

## Platforms tested on

- [x] WPF .NET 8
- [x] WPF Framework
- [x] WinUI
- [x] MAUI WinUI
- [x] MAUI Android
- [x] MAUI iOS
- [x] MAUI MacCatalyst

## Checklist

- [x] Self-review of changes
- [x] All changes work as expected on all affected platforms
- [x] There are no warnings related to changes
- [x] Code is commented and follows .NET conventions and standards
- [x] Codemaid and XAML styler extensions have been run on every changed file
- [x] No unrelated changes have been made to any other code or project files
- [x] Screenshots are correct size and display in description tab (800 x 600 on Windows, MAUI mobile platforms use the MAUI Windows screenshot)

2024-05-07 10:31 UTC, duffh commented
Reviewers please review files in Geometry/SnapGeometryEdits

2024-05-07 18:14 UTC, williambohrmann3 requested changes
This is an excellent sample. UI looks fantastic. Tested on WPF and MAUI Android (landscape works as well 😃), everything seems to be functioning correctly. My feedback is focused on comments which applies to all implementations.

2024-05-07 18:14 UTC, williambohrmann3 commented on src/WinUI/ArcGIS.WinUI.Viewer/Samples/Geometry/SnapGeometryEdits/SnapGeometryEdits.xaml.cs
> +
Button changes color when pressed on MAUI sample to indicate that geometry editor is started with this geometry type. Can this be added to WinUI and WPF implementations?

2024-05-08 13:23 UTC, Luiy0 approved these changes
Looks great @duffh! I was able to test it with the .NET sample viewer. I've left some minor comments. Thanks!

2024-05-08 13:23 UTC, Luiy0 commented on src/WinUI/ArcGIS.WinUI.Viewer/Samples/Geometry/SnapGeometryEdits/SnapGeometryEdits.jpg
It would be good to have an image showing snapping feedback either for the vertex or line. For the touch screen versions of the app, maybe we want an image showing the magnifier but I'm not sure.

2024-05-08 13:23 UTC, Luiy0 commented on src/WinUI/ArcGIS.WinUI.Viewer/Samples/Geometry/SnapGeometryEdits/SnapGeometryEdits.xaml
> +</UserControl>
newline

2024-05-08 13:23 UTC, Luiy0 commented on src/WPF/WPF.Viewer/Samples/Geometry/SnapGeometryEdits/readme.metadata.json
> +}
newline

2024-05-08 13:23 UTC, Luiy0 commented on src/WPF/WPF.Viewer/Samples/Geometry/SnapGeometryEdits/readme.md
> +For SDKs which added enhanced feedback at 200.3 (Java, QT, .NET, Swift): Snapping can be used during interactive edits that move existing vertices using the `VertexTool`. It is also supported for add
We can tailor this paragraph to fit this particular SDK.

```suggestion
Snapping can be used during interactive edits that move existing vertices using the `VertexTool`. It is also supported for adding new vertices for input devices with a hover event (such as a mouse move without a mouse button press). Using the magnifier to perform a vertex move allows users of touch devices to clearly see the visual cues for snapping.
```

2024-05-08 13:23 UTC, Luiy0 commented on src/WPF/WPF.Viewer/Samples/Geometry/SnapGeometryEdits/readme.md
> +For SDKs which did not add enhanced feedback yet (Kotlin): Snapping can be used during interactive edits that move existing vertices using the `VertexTool`. Using the magnifier to perform the vertex
This can probably be removed as it's covered above.

```suggestion
```

2024-05-08 13:23 UTC, Luiy0 commented on src/MAUI/Maui.Samples/Samples/Geometry/SnapGeometryEdits/SnapGeometryEdits.xaml
> +</ContentPage>
newline

2024-05-08 13:23 UTC, Luiy0 commented on src/MAUI/Maui.Samples/Samples/Geometry/SnapGeometryEdits/SnapGeometryEdits.xaml.cs
> +}
newline

2024-05-08 13:23 UTC, Luiy0 commented on src/MAUI/Maui.Samples/Samples/Geometry/SnapGeometryEdits/readme.metadata.json
> +}
newline

2024-05-08 13:23 UTC, Luiy0 commented on src/WinUI/ArcGIS.WinUI.Viewer/Samples/Geometry/SnapGeometryEdits/SnapGeometryEdits.xaml.cs
> +}
newline

2024-05-08 13:23 UTC, Luiy0 commented on src/WinUI/ArcGIS.WinUI.Viewer/Samples/Geometry/SnapGeometryEdits/readme.metadata.json
> +}
newline

2024-05-08 18:49 UTC, williambohrmann3 approved these changes

2024-05-09 10:07 UTC, merged